// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod patina {
    pub mod measure {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod measure {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct Metric {
                pub name: _rt::String,
                pub value: f64,
                pub labels: _rt::Vec<(_rt::String, _rt::String)>,
            }
            impl ::core::fmt::Debug for Metric {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Metric")
                        .field("name", &self.name)
                        .field("value", &self.value)
                        .field("labels", &self.labels)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn emit(metric: &Metric) -> Result<(), _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let Metric { name: name0, value: value0, labels: labels0 } = metric;
                    let vec1 = name0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec5 = labels0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t2_0, t2_1) = e;
                            let vec3 = t2_0;
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = t2_1;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    let ptr6 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "patina:measure/measure@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "emit"]
                        fn wit_import7(
                            _: *mut u8,
                            _: usize,
                            _: f64,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import7(
                        _: *mut u8,
                        _: usize,
                        _: f64,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import7(
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_f64(value0),
                            result5,
                            len5,
                            ptr6,
                        )
                    };
                    let l8 = i32::from(*ptr6.add(0).cast::<u8>());
                    let result12 = match l8 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l9 = *ptr6
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l10 = *ptr6
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                _rt::string_lift(bytes11)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout5.size() != 0 {
                        _rt::alloc::dealloc(result5.cast(), layout5);
                    }
                    result12
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn gauge(name: &str, value: f64) -> Result<(), _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "patina:measure/measure@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "gauge"]
                        fn wit_import2(_: *mut u8, _: usize, _: f64, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: f64,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(ptr0.cast_mut(), len0, _rt::as_f64(&value), ptr1)
                    };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn counter(name: &str, delta: f64) -> Result<(), _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "patina:measure/measure@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "counter"]
                        fn wit_import2(_: *mut u8, _: usize, _: f64, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: f64,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(ptr0.cast_mut(), len0, _rt::as_f64(&delta), ptr1)
                    };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
        }
    }
    pub mod watch {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum ChangeKind {
                Created,
                Modified,
                Deleted,
            }
            impl ::core::fmt::Debug for ChangeKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ChangeKind::Created => {
                            f.debug_tuple("ChangeKind::Created").finish()
                        }
                        ChangeKind::Modified => {
                            f.debug_tuple("ChangeKind::Modified").finish()
                        }
                        ChangeKind::Deleted => {
                            f.debug_tuple("ChangeKind::Deleted").finish()
                        }
                    }
                }
            }
            impl ChangeKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> ChangeKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => ChangeKind::Created,
                        1 => ChangeKind::Modified,
                        2 => ChangeKind::Deleted,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct FileChange {
                pub watcher: _rt::String,
                pub stream_name: _rt::String,
                pub change_kind: ChangeKind,
                pub absolute_path: _rt::String,
                pub relative_path: _rt::String,
                pub size_bytes: Option<u64>,
                pub modified_unix_ms: Option<u64>,
                pub sha256: Option<_rt::String>,
                pub detected_at: _rt::String,
            }
            impl ::core::fmt::Debug for FileChange {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("FileChange")
                        .field("watcher", &self.watcher)
                        .field("stream-name", &self.stream_name)
                        .field("change-kind", &self.change_kind)
                        .field("absolute-path", &self.absolute_path)
                        .field("relative-path", &self.relative_path)
                        .field("size-bytes", &self.size_bytes)
                        .field("modified-unix-ms", &self.modified_unix_ms)
                        .field("sha256", &self.sha256)
                        .field("detected-at", &self.detected_at)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod wasi {
    pub mod logging {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logging {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Level {
                Trace,
                Debug,
                Info,
                Warn,
                Error,
                Critical,
            }
            impl ::core::fmt::Debug for Level {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Level::Trace => f.debug_tuple("Level::Trace").finish(),
                        Level::Debug => f.debug_tuple("Level::Debug").finish(),
                        Level::Info => f.debug_tuple("Level::Info").finish(),
                        Level::Warn => f.debug_tuple("Level::Warn").finish(),
                        Level::Error => f.debug_tuple("Level::Error").finish(),
                        Level::Critical => f.debug_tuple("Level::Critical").finish(),
                    }
                }
            }
            impl Level {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Level {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Level::Trace,
                        1 => Level::Debug,
                        2 => Level::Info,
                        3 => Level::Warn,
                        4 => Level::Error,
                        5 => Level::Critical,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log(level: Level, context: &str, message: &str) -> () {
                unsafe {
                    let vec0 = context;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "wasi:logging/logging@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(
                            level.clone() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                        )
                    };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod patina {
        pub mod watch {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod events {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type FileChange = super::super::super::super::patina::watch::types::FileChange;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_emit_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len2 = l1;
                    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                    let l3 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len5 = l4;
                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                    let l6 = i32::from(
                        *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l7 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l8 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len9 = l8;
                    let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                    let l10 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l11 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len12 = l11;
                    let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);
                    let l13 = i32::from(
                        *arg0
                            .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l15 = i32::from(
                        *arg0
                            .add(24 + 8 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l17 = i32::from(
                        *arg0
                            .add(40 + 8 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l21 = *arg0
                        .add(40 + 11 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l22 = *arg0
                        .add(40 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len23 = l22;
                    let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);
                    let result24 = T::emit(super::super::super::super::patina::watch::types::FileChange {
                        watcher: _rt::string_lift(bytes2),
                        stream_name: _rt::string_lift(bytes5),
                        change_kind: super::super::super::super::patina::watch::types::ChangeKind::_lift(
                            l6 as u8,
                        ),
                        absolute_path: _rt::string_lift(bytes9),
                        relative_path: _rt::string_lift(bytes12),
                        size_bytes: match l13 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l14 = *arg0
                                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>();
                                    l14 as u64
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        modified_unix_ms: match l15 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l16 = *arg0
                                        .add(32 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>();
                                    l16 as u64
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        sha256: match l17 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l18 = *arg0
                                        .add(40 + 9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l19 = *arg0
                                        .add(40 + 10 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len20 = l19;
                                    let bytes20 = _rt::Vec::from_raw_parts(
                                        l18.cast(),
                                        len20,
                                        len20,
                                    );
                                    _rt::string_lift(bytes20)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        detected_at: _rt::string_lift(bytes23),
                    });
                    _rt::cabi_dealloc(
                        arg0,
                        48 + 12 * ::core::mem::size_of::<*const u8>(),
                        8,
                    );
                    let ptr25 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result24 {
                        Ok(_) => {
                            *ptr25.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr25.add(0).cast::<u8>() = (1i32) as u8;
                            let vec26 = (e.into_bytes()).into_boxed_slice();
                            let ptr26 = vec26.as_ptr().cast::<u8>();
                            let len26 = vec26.len();
                            ::core::mem::forget(vec26);
                            *ptr25
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len26;
                            *ptr25
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr26.cast_mut();
                        }
                    };
                    ptr25
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_emit<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn emit(change: FileChange) -> Result<(), _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_patina_watch_events_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "patina:watch/events@0.1.0#emit")] unsafe extern "C" fn
                        export_emit(arg0 : * mut u8,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_emit_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_patina:watch/events@0.1.0#emit")] unsafe extern "C" fn
                        _post_return_emit(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_emit::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_patina_watch_events_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_watch_null_sink_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::patina::watch::events::__export_patina_watch_events_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::patina::watch::events);
    };
}
#[doc(inline)]
pub(crate) use __export_watch_null_sink_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:patina:watch-null-sink@0.1.0:watch-null-sink:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 794] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x94\x05\x01A\x02\x01\
A\x09\x01B\x04\x01m\x06\x05trace\x05debug\x04info\x04warn\x05error\x08critical\x04\
\0\x05level\x03\0\0\x01@\x03\x05level\x01\x07contexts\x07messages\x01\0\x04\0\x03\
log\x01\x02\x03\0\x1awasi:logging/logging@0.1.0\x05\0\x01B\x0b\x01o\x02ss\x01p\0\
\x01r\x03\x04names\x05valueu\x06labels\x01\x04\0\x06metric\x03\0\x02\x01j\0\x01s\
\x01@\x01\x06metric\x03\0\x04\x04\0\x04emit\x01\x05\x01@\x02\x04names\x05valueu\0\
\x04\x04\0\x05gauge\x01\x06\x01@\x02\x04names\x05deltau\0\x04\x04\0\x07counter\x01\
\x07\x03\0\x1cpatina:measure/measure@0.1.0\x05\x01\x01B\x06\x01m\x03\x07created\x08\
modified\x07deleted\x04\0\x0bchange-kind\x03\0\0\x01kw\x01ks\x01r\x09\x07watcher\
s\x0bstream-names\x0bchange-kind\x01\x0dabsolute-paths\x0drelative-paths\x0asize\
-bytes\x02\x10modified-unix-ms\x02\x06sha256\x03\x0bdetected-ats\x04\0\x0bfile-c\
hange\x03\0\x04\x03\0\x18patina:watch/types@0.1.0\x05\x02\x02\x03\0\x02\x0bfile-\
change\x01B\x05\x02\x03\x02\x01\x03\x04\0\x0bfile-change\x03\0\0\x01j\0\x01s\x01\
@\x01\x06change\x01\0\x02\x04\0\x04emit\x01\x03\x04\0\x19patina:watch/events@0.1\
.0\x05\x04\x04\0,patina:watch-null-sink/watch-null-sink@0.1.0\x04\0\x0b\x15\x01\0\
\x0fwatch-null-sink\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compo\
nent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
